repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: check-json
    exclude: ^frontend/node_modules/
  - id: check-ast
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/asottile/add-trailing-comma
  rev: v4.0.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.16.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --preserve-quotes]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.15.0'
  hooks:
  - id: ruff
    args: [--fix, --config, backend/pyproject.toml]
  - id: ruff-format
    args: [--config, backend/pyproject.toml]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.19.1
  hooks:
  - id: mypy
    args: [--config-file, backend/pyproject.toml]

exclude: |
  (?x)(
      ^backend/models/|
      ^backend/data/|
      ^frontend/node_modules/
  )
